#
#     (C) Rasmus Munk Larsen, Stanford University, 2004
#
### Object files.

TYPE_DIR = double
TYPE_PREFIX = d
REAL_DIR = $(TYPE_DIR)
REAL_TYPE_PREFIX = $(TYPE_PREFIX)
include ../Make/Makefile_lib_template.inc
